stages: [build]

variables:
  POSTGRES_DB: mini_stream
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: $PGPASSWORD

services:
  - name: postgres:16
    alias: db

build:
  stage: build
  image: postgres:16
  script:
    - apt-get update && apt-get install -y postgresql-client
    - export DATABASE_URL="postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB"
    - psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f scripts/10_tables.sql
    - psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f scripts/20_indexes.sql
    - psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f scripts/30_seed_static.sql
    - psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f scripts/31_seed_users.sql
    - psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f scripts/32_seed_links.sql
    - psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f scripts/33_seed_facts.sql
    - psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f scripts/99_smoke.sql
